# Generated by Django 5.2.3 on 2025-06-23 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NonConformanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان عدم المطابقة')),
                ('description', models.TextField(verbose_name='وصف تفصيلي للمشكلة')),
                ('source', models.CharField(choices=[('INTERNAL_AUDIT', 'تدقيق داخلي'), ('EXTERNAL_AUDIT', 'تدقيق خارجي'), ('CUSTOMER_COMPLAINT', 'شكوى عميل'), ('INTERNAL_TEST', 'فحص داخلي'), ('OTHER', 'مصدر آخر')], max_length=50, verbose_name='مصدر التقرير')),
                ('status', models.CharField(choices=[('OPEN', 'مفتوح'), ('UNDER_INVESTIGATION', 'قيد التحقيق'), ('CAPA_OPEN', 'إجراء تصحيحي مفتوح'), ('CLOSED', 'مغلق')], default='OPEN', max_length=50, verbose_name='حالة التقرير')),
                ('reported_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإبلاغ')),
                ('related_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.document', verbose_name='الوثيقة ذات الصلة')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='صاحب البلاغ')),
            ],
            options={
                'verbose_name': 'تقرير عدم مطابقة',
                'verbose_name_plural': 'تقارير عدم المطابقة',
                'ordering': ['-reported_at'],
            },
        ),
    ]
