# Generated by Django 5.2.3 on 2025-06-23 08:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان أو نطاق التدقيق')),
                ('audit_type', models.CharField(choices=[('INTERNAL', 'تدقيق داخلي'), ('EXTERNAL', 'تدقيق خارجي'), ('SUPPLIER', 'تدقيق مورد')], max_length=50, verbose_name='نوع التدقيق')),
                ('status', models.CharField(choices=[('PLANNED', 'مخطط له'), ('IN_PROGRESS', 'قيد التنفيذ'), ('COMPLETED', 'مكتمل'), ('CANCELLED', 'ملغى')], default='PLANNED', max_length=50, verbose_name='حالة التدقيق')),
                ('planned_start_date', models.DateField(verbose_name='تاريخ البدء المخطط له')),
                ('planned_end_date', models.DateField(verbose_name='تاريخ الانتهاء المخطط له')),
                ('actual_start_date', models.DateField(blank=True, null=True, verbose_name='تاريخ البدء الفعلي')),
                ('actual_end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء الفعلي')),
                ('lead_auditor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='المدقق الرئيسي')),
            ],
            options={
                'verbose_name': 'تدقيق',
                'verbose_name_plural': 'عمليات التدقيق',
            },
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finding_type', models.CharField(choices=[('OBSERVATION', 'ملاحظة'), ('MINOR_NC', 'عدم مطابقة صغرى'), ('MAJOR_NC', 'عدم مطابقة كبرى')], max_length=50, verbose_name='نوع الملاحظة')),
                ('description', models.TextField(verbose_name='وصف الملاحظة')),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='audits.audit', verbose_name='التدقيق التابع له')),
            ],
            options={
                'verbose_name': 'ملاحظة تدقيق',
                'verbose_name_plural': 'ملاحظات التدقيق',
            },
        ),
    ]
