# Generated by Django 5.2.3 on 2025-06-23 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان التدريب')),
                ('description', models.TextField(blank=True, verbose_name='وصف التدريب')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='تاريخ إنشاء التدريب')),
                ('related_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.document', verbose_name='الوثيقة التدريبية')),
            ],
            options={
                'verbose_name': 'تدريب',
                'verbose_name_plural': 'التدريبات',
            },
        ),
        migrations.CreateModel(
            name='TrainingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ASSIGNED', 'معين'), ('IN_PROGRESS', 'قيد الإنجاز'), ('COMPLETED', 'مكتمل'), ('OVERDUE', 'متأخر')], default='ASSIGNED', max_length=50, verbose_name='حالة التدريب')),
                ('assigned_date', models.DateField(auto_now_add=True, verbose_name='تاريخ التعيين')),
                ('due_date', models.DateField(verbose_name='تاريخ الاستحقاق')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الإكمال')),
                ('evidence', models.FileField(blank=True, null=True, upload_to='training_evidence/', verbose_name='إثبات الإكمال')),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المتدرب')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.training', verbose_name='التدريب')),
            ],
            options={
                'verbose_name': 'سجل تدريبي',
                'verbose_name_plural': 'السجلات التدريبية',
                'unique_together': {('trainee', 'training')},
            },
        ),
    ]
